import { useEffect, useState } from "react";

const API_URL = "http://127.0.0.1:8000";

function Opportunities() {
  const [opportunities, setOpportunities] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const loadOpportunities = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await fetch(`${API_URL}/opportunities/`);

      if (!response.ok) {
        throw new Error("Failed to load opportunities");
      }

      const data = await response.json();

      console.log("Opportunities:", data);

      setOpportunities(data);
    } catch (err) {
      console.error("Opportunities error:", err);
      setError("Unable to load trading opportunities.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadOpportunities();
  }, []);

  const formatMoney = (value) => {
    if (value === null || value === undefined) {
      return "—";
    }

    return `₹${Number(value).toLocaleString("en-IN", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}`;
  };

  const signalClass = (signal) => {
    if (signal === "BUY") {
      return "signal-buy";
    }

    if (signal === "SELL") {
      return "signal-sell";
    }

    return "signal-wait";
  };

  const strengthClass = (strength) => {
    if (strength?.toLowerCase().includes("strong buy")) {
      return "strength-strong-buy";
    }

    if (strength?.toLowerCase().includes("buy")) {
      return "strength-buy";
    }

    if (strength?.toLowerCase().includes("strong sell")) {
      return "strength-strong-sell";
    }

    if (strength?.toLowerCase().includes("sell")) {
      return "strength-sell";
    }

    return "strength-wait";
  };

  return (
    <section className="page-content">

      {/* Header */}
      <div className="page-heading">

        <div>
          <p className="eyebrow">AI TRADING INTELLIGENCE</p>

          <h1>
            Opportunities
          </h1>

          <p>
            Ranked trading opportunities generated by the AI decision engine.
          </p>
        </div>

        <button
          className="scan-button"
          onClick={loadOpportunities}
          disabled={loading}
        >
          {loading ? "Refreshing..." : "↻ Refresh"}
        </button>

      </div>


      {/* Error */}
      {error && (
        <div className="error-message">
          {error}
        </div>
      )}


      {/* Summary */}
      <div className="scanner-summary">

        <div className="stat-card">

          <span className="stat-label">
            Opportunities
          </span>

          <strong>
            {opportunities.length}
          </strong>

          <small>
            Ranked setups
          </small>

        </div>


        <div className="stat-card">

          <span className="stat-label">
            Buy Setups
          </span>

          <strong>
            {
              opportunities.filter(
                (item) => item.signal === "BUY"
              ).length
            }
          </strong>

          <small className="positive">
            Bullish opportunities
          </small>

        </div>


        <div className="stat-card">

          <span className="stat-label">
            Sell Setups
          </span>

          <strong>
            {
              opportunities.filter(
                (item) => item.signal === "SELL"
              ).length
            }
          </strong>

          <small className="negative">
            Bearish opportunities
          </small>

        </div>


        <div className="stat-card">

          <span className="stat-label">
            Highest Score
          </span>

          <strong>
            {opportunities.length
              ? Math.max(
                  ...opportunities.map(
                    (item) => item.score
                  )
                )
              : "—"}
          </strong>

          <small>
            AI opportunity score
          </small>

        </div>

      </div>


      {/* Opportunity table */}
      <div className="panel opportunities-table-panel">

        <div className="panel-header">

          <div>

            <span className="panel-label">
              RANKED OPPORTUNITIES
            </span>

            <h2>
              AI Opportunity Engine
            </h2>

          </div>

          <span className="live-badge">
            LIVE
          </span>

        </div>


        {loading ? (

          <div className="empty-state">
            <p>Loading opportunities...</p>
          </div>

        ) : opportunities.length === 0 ? (

          <div className="empty-state">

            <p>
              No opportunities available.
            </p>

            <small>
              Generate signals and scan the market first.
            </small>

          </div>

        ) : (

          <div className="opportunities-table">

            <div className="opportunity-table-row opportunity-table-head">

              <span>#</span>
              <span>Symbol</span>
              <span>Signal</span>
              <span>Strength</span>
              <span>Confidence</span>
              <span>Score</span>
              <span>Trend</span>
              <span>Entry</span>
              <span>Stop Loss</span>
              <span>Target</span>
              <span>R:R</span>

            </div>


            {opportunities.map((opportunity) => (

              <div
                className="opportunity-table-row"
                key={opportunity.symbol}
              >

                <span className="scanner-rank">
                  {String(opportunity.rank).padStart(2, "0")}
                </span>


                <strong>
                  {opportunity.symbol}
                </strong>


                <span
                  className={signalClass(
                    opportunity.signal
                  )}
                >
                  {opportunity.signal}
                </span>


                <span
                  className={strengthClass(
                    opportunity.strength
                  )}
                >
                  {opportunity.strength}
                </span>


                <span>
                  {opportunity.confidence}%
                </span>


                <span>
                  {opportunity.score}
                </span>


                <span>
                  {opportunity.trend}
                </span>


                <span>
                  {formatMoney(opportunity.entry)}
                </span>


                <span>
                  {formatMoney(
                    opportunity.stop_loss
                  )}
                </span>


                <span>
                  {formatMoney(
                    opportunity.target
                  )}
                </span>


                <span>
                  {opportunity.risk_reward ?? "—"}
                </span>

              </div>

            ))}

          </div>

        )}

      </div>

    </section>
  );
}

export default Opportunities;