import { useEffect, useState } from "react";

const API_URL = "http://127.0.0.1:8000";

function Scanner() {
  const [results, setResults] = useState([]);
  const [scanning, setScanning] = useState(false);
  const [error, setError] = useState("");

  const scanMarket = async () => {
    try {
      setScanning(true);
      setError("");

      const response = await fetch(`${API_URL}/scanner/`);

      if (!response.ok) {
        throw new Error("Scanner request failed");
      }

      const data = await response.json();
      setResults(data);
    } catch (err) {
      console.error("Scanner error:", err);
      setError("Unable to scan the market.");
    } finally {
      setScanning(false);
    }
  };

  useEffect(() => {
    scanMarket();
  }, []);

  return (
    <section className="page-content">
      <div className="page-heading">
        <div>
          <p className="eyebrow">MARKET INTELLIGENCE</p>
          <h1>Market Scanner</h1>
          <p>
            Ranked opportunities generated by the decision engine.
          </p>
        </div>

        <button
          className="scan-button"
          onClick={scanMarket}
          disabled={scanning}
        >
          {scanning ? "Scanning..." : "✦ Scan Market"}
        </button>
      </div>

      {error && (
        <div className="error-message">
          {error}
        </div>
      )}

      <div className="scanner-summary">
        <div className="stat-card">
          <span className="stat-label">Markets Scanned</span>
          <strong>{results.length}</strong>
          <small>Current scanner universe</small>
        </div>

        <div className="stat-card">
          <span className="stat-label">Buy Signals</span>
          <strong>
            {results.filter((item) => item.signal === "BUY").length}
          </strong>
          <small className="positive">Bullish setups</small>
        </div>

        <div className="stat-card">
          <span className="stat-label">Sell Signals</span>
          <strong>
            {results.filter((item) => item.signal === "SELL").length}
          </strong>
          <small className="negative">Bearish setups</small>
        </div>

        <div className="stat-card">
          <span className="stat-label">Highest Confidence</span>
          <strong>
            {results.length
              ? `${Math.max(...results.map((item) => item.confidence))}%`
              : "—"}
          </strong>
          <small>Top-ranked setup</small>
        </div>
      </div>

      <div className="panel scanner-panel">
        <div className="panel-header">
          <div>
            <span className="panel-label">RANKED RESULTS</span>
            <h2>Market Opportunities</h2>
          </div>

          <span className="live-badge">
            {scanning ? "SCANNING" : "LIVE"}
          </span>
        </div>

        {results.length === 0 && !scanning ? (
          <div className="empty-state">
            <p>No scanner results available.</p>
            <small>Run the market scan to generate opportunities.</small>
          </div>
        ) : (
          <div className="scanner-table">
            <div className="scanner-row scanner-head">
              <span>#</span>
              <span>Symbol</span>
              <span>Signal</span>
              <span>Confidence</span>
              <span>Trend</span>
              <span>Entry</span>
              <span>Stop Loss</span>
              <span>Target</span>
              <span>R:R</span>
            </div>

            {results.map((item, index) => (
              <div
                className="scanner-row"
                key={`${item.symbol}-${index}`}
              >
                <span className="scanner-rank">
                  {String(index + 1).padStart(2, "0")}
                </span>

                <strong>{item.symbol}</strong>

                <span className={item.signal === "BUY"
                  ? "signal-buy"
                  : item.signal === "SELL"
                  ? "signal-sell"
                  : "signal-wait"}
                >
                  {item.signal}
                </span>

                <span>
                  {item.confidence}%
                </span>

                <span>
                  {item.trend}
                </span>

                <span>
                  {item.entry != null
                    ? `₹${Number(item.entry).toLocaleString("en-IN")}`
                    : "—"}
                </span>

                <span>
                  {item.stop_loss != null
                    ? `₹${Number(item.stop_loss).toLocaleString("en-IN")}`
                    : "—"}
                </span>

                <span>
                  {item.target != null
                    ? `₹${Number(item.target).toLocaleString("en-IN")}`
                    : "—"}
                </span>

                <span>
                  {item.risk_reward != null
                    ? item.risk_reward
                    : "—"}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}

export default Scanner;